import { test, expect, type Page } from '@playwright/test'
const initial = 'initial-browser-password-839!'
const replacement = 'replacement-browser-password-742!'
async function login(page: Page, name: string, password: string) {
  await page.getByLabel('Organization code').fill('browser-test')
  await page.getByLabel('Login', { exact: true }).fill(name)
  await page.getByLabel('Password', { exact: true }).fill(password)
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
}
async function change(page: Page) {
  await page.getByLabel('Current password').fill(initial)
  await page.getByLabel('New password', { exact: true }).fill(replacement)
  await page.getByRole('button', { name: 'Change password', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Workspace', exact: true })).toBeVisible()
}
test('bootstrap, forced change, restore, admin disable, logout and mobile login', async ({ page, browser }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await expect.poll(async () => { try { return (await page.request.get('/')).status() } catch { return 0 } }).toBe(200)
  await expect.poll(async () => { try { return (await page.request.get('/api/me')).status() } catch { return 0 } }, { timeout: 15000 }).toBe(401)
  await page.goto('/')
  await expect(page).toHaveTitle('QuotePilot')
  await expect(page.getByRole('heading', { name: 'Sign in', exact: true })).toBeVisible()
  await login(page, 'admin', 'invalid-password')
  await expect(page.getByRole('alert')).toContainText('Unable to sign in')
  await login(page, 'admin', initial)
  await expect(page.getByRole('heading', { name: 'Change your initial password' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Manage users' })).toHaveCount(0)
  await change(page)
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Manage users' })).toBeVisible()
  await page.screenshot({ path: testInfo.outputPath('admin.png'), fullPage: true })
  await page.getByLabel('New user login').fill('sales')
  await page.getByLabel('Initial password', { exact: true }).fill(initial)
  await page.getByRole('button', { name: 'Create user', exact: true }).click()
  await expect(page.locator('li').filter({ hasText: 'sales' })).toBeVisible()
  const context = await browser.newContext()
  const sales = await context.newPage()
  await sales.goto('http://127.0.0.1:5174/')
  await login(sales, 'sales', initial)
  await change(sales)
  await expect(sales.getByRole('heading', { name: 'Manage users' })).toHaveCount(0)
  await page.getByRole('button', { name: 'Refresh users' }).click()
  await page.locator('li').filter({ hasText: 'sales' }).getByRole('button', { name: 'Disable', exact: true }).click()
  await expect(page.locator('li').filter({ hasText: 'sales' })).toContainText('Disabled')
  await sales.getByRole('button', { name: 'Keep working' }).click()
  await expect(sales.getByRole('heading', { name: 'Sign in', exact: true })).toBeVisible()
  await login(sales, 'sales', replacement)
  await expect(sales.getByRole('alert')).toContainText('Unable to sign in')
  await page.getByRole('button', { name: 'Log out' }).click()
  await expect(page.getByRole('heading', { name: 'Sign in', exact: true })).toBeVisible()
  await page.reload()
  await expect(page.getByRole('heading', { name: 'Sign in', exact: true })).toBeVisible()
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(page.getByRole('button', { name: 'Sign in', exact: true })).toBeVisible()
  expect(await page.locator('body').evaluate(el => el.scrollWidth <= window.innerWidth)).toBeTruthy()
  expect(errors).toEqual([])
  await page.screenshot({ path: testInfo.outputPath('mobile-login.png'), fullPage: true })
  await context.close()
})
