import { test, expect } from '@playwright/test'

test('restart: reopen captured quote and save a new revision', async ({ page }, info) => {
  await expect.poll(async () => { try { return (await page.request.get('/api/me')).status() } catch { return 0 } }).toBe(401)
  await page.goto('/')
  await page.getByLabel('Organization code').fill('browser-test')
  await page.getByLabel('Login', { exact: true }).fill('admin')
  await page.getByLabel('Password', { exact: true }).fill('replacement-browser-password-742!')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByRole('button', { name: 'Refresh users' }).click()
  await page.locator('li').filter({ hasText: 'sales' }).getByRole('button', { name: 'Enable', exact: true }).click()
  await expect(page.locator('li').filter({ hasText: 'sales' })).toContainText('Active')
  await page.getByRole('button', { name: 'Log out' }).click()
  await page.getByLabel('Organization code').fill('browser-test')
  await page.getByLabel('Login', { exact: true }).fill('sales')
  await page.getByLabel('Password', { exact: true }).fill('replacement-browser-password-742!')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await page.getByLabel('Open saved draft', { exact: true }).selectOption({ index: 1 })
  await expect(page.getByLabel('Quantity', { exact: true })).toHaveValue('2')
  await expect(page.getByText(/Normal reference: 10.*Negotiated proposal: 9.50/).first()).toBeVisible()
  await expect(page.getByText('Settings changed — revalidation required', { exact: true })).toBeVisible()
  // Two real browser editors start from the same saved version.
  const other = await page.context().newPage()
  await other.goto('/')
  await other.getByLabel('Open saved draft', { exact: true }).selectOption({ index: 1 })
  await page.getByLabel('Quantity', { exact: true }).fill('3')
  await page.getByRole('button', { name: 'Save new revision', exact: true }).click()
  await expect(page.getByText(/saved revision 2/)).toBeVisible()
  await other.getByLabel('Quantity', { exact: true }).fill('4')
  await other.getByRole('button', { name: 'Save new revision', exact: true }).click()
  await expect(other.getByText('Concurrent edit conflict', { exact: true })).toBeVisible()
  await expect(other.getByLabel('Quantity', { exact: true })).toHaveValue('4')
  await other.getByRole('button', { name: 'Reload latest (replaces local edits)' }).click()
  await expect(other.getByLabel('Quantity', { exact: true })).toHaveValue('3')
  await other.close()
  await page.getByRole('button', { name: 'Preview draft', exact: true }).click()
  await expect(page.getByRole('region', { name: 'Draft preview' })).toContainText('28.50')
  await expect(page.getByRole('button', { name: /Generate|Send|Approve/ })).toHaveCount(0)
  await page.screenshot({ path: info.outputPath('quote-after-restart.png'), fullPage: true })
})

